A=float(input('enter a number: '))
B=float(input('enter a number: '))
C=float(input('enter a number: '))
num1="%.1f"%A
num2="%.1f"%B
num3="%.1f"%C
sum=float(num1)+float(num2)+float(num3)
ans=(sum/3)
print('MEDIA = %s'%"%.1f"%ans)